apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.12.3  # Upewnij się, że używasz aktualnej wersji charta
    helm:
      parameters:
        - name: installCRDs
          value: "true"  # Ważne dla instalacji CRDs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
