apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system  # Możesz zmienić na preferowaną przestrzeń nazw
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.23.0  # Upewnij się, że używasz istniejącej wersji
    chart: sealed-secrets
    helm:
      values: |
        # Tutaj możesz dodać dodatkowe wartości konfiguracyjne dla Helm, jeśli potrzebujesz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
