apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets  # Zmień namespace na właściwy, jeśli potrzebne
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets  # Sprawdź poprawność repo
    targetRevision: v0.21.0
    path: charts/sealed-secrets  # Upewnij się, że ścieżka jest poprawna
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
