apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system  # Możesz zmienić na preferowaną przestrzeń nazw
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: sealed-secrets
    targetRevision: 2.6.1  # Ustaw istniejącą wersję charta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
